version: '2.4'
services:
  ib-gateway:
    image: docker.io/omdv/ib-gateway:978
    environment:
      - VNC_PASSWORD=${TWS_VNC_PASSWORD}
      - TWSUSERID=${TWS_USER_ID_PAPER}
      - TWSPASSWORD=${TWS_PASSWORD_PAPER}
      - TRADING_MODE=paper
    restart: always
    ports:
    - 8888:80
    - 4000:4000

  ib-app:
    image: gcr.io/ibkr-trading/ib-app:v001
    environment:
      - IB_GATEWAY_HOST=ib-gateway
      - TRADING_MODE=paper
    restart: on-failure
    depends_on:
    - ib-gateway