version: '2.4'
services:
  ib-gateway:
    build: ./gateway
    environment:
      - VNC_PASSWORD=${TWS_VNC_PASSWORD}
      - TWSUSERID=${TWS_USER_ID_PAPER}
      - TWSPASSWORD=${TWS_PASSWORD_PAPER}
      - TRADING_MODE=paper
    restart: always
    ports:
    - 8888:80
    - 4041:4041
    - 4042:4042

  ib-app:
    build: ./application
    environment:
      - IB_GATEWAY_HOST=ib-gateway
      - TRADING_MODE=paper
    restart: on-failure
    depends_on:
    - ib-gateway