version: '2.4'
services:
  tailscale:
    hostname: ibgateway
    image: richnorth/tailscale:v0.99.1
    volumes:
        - "./tailscale_var_lib:/var/lib"
        - "/dev/net/tun:/dev/net/tun"
    cap_add:
      - net_admin
      - sys_module
    command: tailscaled

  ibgateway:
    build: ./gateway/
    environment:
      - VNC_PASSWORD=${TWS_VNC_PASSWORD}
      - TRADING_MODE=${TWS_TRADING_MODE}
      - TWSUSERID=${TWS_USER_ID}
      - TWSPASSWORD=${TWS_PASSWORD}
    restart: always
    depends_on:
    - tailscale
    network_mode: service:tailscale

  application:
    build: ./application/
    restart: on-failure
    depends_on:
    - ibgateway
    network_mode: service:tailscale